// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YemekTarifiContext.Data.Context;

#nullable disable

namespace YemekTarifGenerator.Data.Migrations
{
    [DbContext(typeof(YemekTarifiGeneratorContext))]
    partial class YemekTarifiGeneratorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YemekTarifiContext.Domain.Entities.Food", b =>
                {
                    b.Property<int>("FoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodID"));

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodRecipe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FoodID");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("YemekTarifiContext.Domain.Entities.FoodMaterial", b =>
                {
                    b.Property<int>("FoodMaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodMaterialID"));

                    b.Property<int>("FoodID")
                        .HasColumnType("int");

                    b.Property<int>("MaterialID")
                        .HasColumnType("int");

                    b.HasKey("FoodMaterialID");

                    b.HasIndex("FoodID");

                    b.HasIndex("MaterialID");

                    b.ToTable("FoodMaterials");
                });

            modelBuilder.Entity("YemekTarifiContext.Domain.Entities.Material", b =>
                {
                    b.Property<int>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialID"));

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialID");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("YemekTarifiContext.Domain.Entities.FoodMaterial", b =>
                {
                    b.HasOne("YemekTarifiContext.Domain.Entities.Food", "Food")
                        .WithMany("FoodMaterials")
                        .HasForeignKey("FoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YemekTarifiContext.Domain.Entities.Material", "Material")
                        .WithMany("FoodMaterials")
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("YemekTarifiContext.Domain.Entities.Food", b =>
                {
                    b.Navigation("FoodMaterials");
                });

            modelBuilder.Entity("YemekTarifiContext.Domain.Entities.Material", b =>
                {
                    b.Navigation("FoodMaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
